name: Test environments

on: workflow_dispatch

jobs:
  DEV_DISTRIBUTION:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Print out BUILD_PROPERTIES
        run: |
          echo "Build properties for dev are -> ${{env.BUILD_PROPERTIES}}"
