name: Test environments

on: workflow_dispatch

jobs:
  DEV_DISTRIBUTION:
    runs-on: macos-14
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Print out BUILD_PROPERTIES
        run: |
          echo "Build properties for dev are -> "${{ env.BUILD_PROPERTIES }}""

      - name: Get repo build.properties from secrets
        run: echo "${{secrets.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Get env build.properties from secrets
        run: echo "${{env.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Print out favorite dog type
        run: |
          echo "My favorite dob is a ${{ vars.FAVORITE_DOG_TYPE }}"

      - name: Create build properties
        run: |
          echo "KEY_ONE=\"${{vars.KEY_ONE}}\"" >> $GITHUB_WORKSPACE/build.properties
          echo "KEY_TWO=\"${{vars.KEY_TWO}}\"" >> $GITHUB_WORKSPACE/build.properties
          echo "KEY_THREE=\"${{vars.KEY_THREE}}\"" >> $GITHUB_WORKSPACE/build.properties
          VERSION_CODE=$(date "+%Y%m%d %H:%M")
          echo "VERSION_CODE=\"$VERSION_CODE\"" >> $GITHUB_WORKSPACE/build.properties

      - name: Create unique id for version-code-update branch
        run: |
          version_code_update_branch_id=${{ github.run_id }}
          echo "Run ID -> $version_code_update_branch_id"

      - name: Create the version-code-update branch
        run: |
          git checkout -b version-code-update/$version_code_update_branch_id
          git push origin version-code-update/$version_code_update_branch_id

      - name: Update VERSION_CODE based on current date
        run: |
          compact_month=$(date "+%m" | sed 's/^0//')
          version_code=$(date "+$compact_month%d%Y%H%M")
          sed -i.bak "s/versionCode [0-9]\+/versionCode $version_code/" app/build.gradle

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add app/build.gradle
          git checkout -- .
          git commit -m "Update VERSION_CODE based on current date"

      - name: Push changes
        run: git push origin version-code-update/$version_code_update_branch_id

      - name: Create pull request
        run: |
          gh pr create --base development --head version-code-update/$version_code_update_branch_id --title "Update VERSION_CODE" --body "Automated PR created by GitHub Actions"
          
  STAGING:
    runs-on: ubuntu-latest
    environment: staging
    needs: DEV_DISTRIBUTION

    steps:
      - name: Print out BUILD_PROPERTIES
        run: |
          echo "Build properties for dev are -> "${{ env.BUILD_PROPERTIES }}""

      - name: Get repo build.properties from secrets
        run: echo "${{secrets.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Get env build.properties from secrets
        run: echo "${{env.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Print out favorite dog type
        run: |
          echo "My favorite dob is a ${{ vars.FAVORITE_DOG_TYPE }}"
