name: Test environments

on: workflow_dispatch

jobs:
  DEV_DISTRIBUTION:
    runs-on: macos-14
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Print out BUILD_PROPERTIES
        run: |
          echo "Build properties for dev are -> "${{ env.BUILD_PROPERTIES }}""

      - name: Get repo build.properties from secrets
        run: echo "${{secrets.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Get env build.properties from secrets
        run: echo "${{env.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Print out favorite dog type
        run: |
          echo "My favorite dob is a ${{ vars.FAVORITE_DOG_TYPE }}"

      - name: Create build properties
        run: |
          echo "KEY_ONE=\"${{vars.KEY_ONE}}\"" >> $GITHUB_WORKSPACE/build.properties
          echo "KEY_TWO=\"${{vars.KEY_TWO}}\"" >> $GITHUB_WORKSPACE/build.properties
          echo "KEY_THREE=\"${{vars.KEY_THREE}}\"" >> $GITHUB_WORKSPACE/build.properties

      - name: Print out build.properties
        run: cat $GITHUB_WORKSPACE/build.properties
          
  STAGING:
    runs-on: ubuntu-latest
    environment: staging
    needs: DEV_DISTRIBUTION

    steps:
      - name: Print out BUILD_PROPERTIES
        run: |
          echo "Build properties for dev are -> "${{ env.BUILD_PROPERTIES }}""

      - name: Get repo build.properties from secrets
        run: echo "${{secrets.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Get env build.properties from secrets
        run: echo "${{env.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Print out favorite dog type
        run: |
          echo "My favorite dob is a ${{ vars.FAVORITE_DOG_TYPE }}"
