name: Test environments

on:
  workflow_dispatch:
    inputs:
      customParam:
        type: choice
        description: 'Custom input parameter with choices'
        required: true
        options: 
          - 'app'
          - 'fanaticscollect'

permissions: write-all

jobs:
  DEV_DISTRIBUTION:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Print out branch
        run: echo "Branch -> ${{ github.ref }}"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Print working directory
        run: pwd

      - name: List files in the current directory
        run: ls

      - name: Print out BUILD_PROPERTIES
        run: |
          echo "Build properties for dev are -> "${{ env.BUILD_PROPERTIES }}""

      - name: Get repo build.properties from secrets
        run: echo "${{secrets.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Get env build.properties from secrets
        run: echo "${{env.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Print out favorite dog type
        run: |
          echo "My favorite dob is a ${{ vars.FAVORITE_DOG_TYPE }}"

      - name: Create build properties
        run: |
          echo "KEY_ONE=\"${{vars.KEY_ONE}}\"" >> $GITHUB_WORKSPACE/build.properties
          echo "KEY_TWO=\"${{vars.KEY_TWO}}\"" >> $GITHUB_WORKSPACE/build.properties
          echo "KEY_THREE=\"${{vars.KEY_THREE}}\"" >> $GITHUB_WORKSPACE/build.properties
          VERSION_CODE=$(date "+%Y%m%d %H:%M")
          echo "VERSION_CODE=\"$VERSION_CODE\"" >> $GITHUB_WORKSPACE/build.properties

      - name: Create unique branch name for version-code-update
        run: |
          VERSION_CODE_UPDATE_BRANCH_NAME=version-code-update/${{github.run_id}}
          echo "Branch name -> $VERSION_CODE_UPDATE_BRANCH_NAME"
          git switch -c $VERSION_CODE_UPDATE_BRANCH_NAME
          git push --set-upstream origin $VERSION_CODE_UPDATE_BRANCH_NAME

      - name: Update VERSION_CODE based on current date
        run: |
          compact_month=$(date "+%m" | sed 's/^0//')
          current_year=$(date "+%Y")
          last_two_digits=${current_year:2:2}
          version_code=$(date "+$compact_month%d$last_two_digits%H%M")
          sed -i.bak "s/versionCode = [0-9]/versionCode = $version_code/" app/build.gradle.kts

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add app/build.gradle.kts
          git checkout -- .
          git commit -m "Update VERSION_CODE for run id ${{github.run_id}}"
          git push origin $VERSION_CODE_UPDATE_BRANCH_NAME

      - name: Create pull request
        run: |
          RUN_ID=${{github.run_id}}
          BRANCH_HEAD=version-code-update/${{github.run_id}}
          gh pr create --base development --head $BRANCH_HEAD --title "Update VERSION_CODE for run ID $RUN_ID" --body "Automated PR created by GitHub Actions"
          
  STAGING:
    runs-on: ubuntu-latest
    environment: staging
    needs: DEV_DISTRIBUTION

    steps:
      - name: Print out BUILD_PROPERTIES
        run: |
          echo "Build properties for dev are -> "${{ env.BUILD_PROPERTIES }}""

      - name: Get repo build.properties from secrets
        run: echo "${{secrets.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Get env build.properties from secrets
        run: echo "${{env.BUILD_PROPERTIES}}" > $GITHUB_WORKSPACE/build.properties

      - name: Print out favorite dog type
        run: |
          echo "My favorite dob is a ${{ vars.FAVORITE_DOG_TYPE }}"
